#!/bin/bash
set -e
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

curl -fsSL mgross21.github.io/pomodoro-cli/pomodoro -o "$TEMP_DIR/pomodoro"
chmod +x "$TEMP_DIR/pomodoro"
exec "$TEMP_DIR/pomodoro" "$@"
