name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Build
      run: cargo build --release --locked

    - name: Prepare Deploy Directory
      run: mkdir -p ./target/deploy

    - name: Move Binary
      run: mv ./target/release/pomodoro ./target/deploy/pomodoro

    - name: Create Runner Script
      run: |
        cat > ./target/deploy/run << 'EOF'
        #!/bin/bash
        set -e
        TEMP_DIR=$(mktemp -d)
        trap "rm -rf $TEMP_DIR" EXIT

        curl -fsSL mgross21.github.io/pomodoro-cli/pomodoro -o "$TEMP_DIR/pomodoro"
        chmod +x "$TEMP_DIR/pomodoro"
        exec "$TEMP_DIR/pomodoro" "$@"
        EOF

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/deploy
        force_orphan: true