name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Build
      run: cargo build --release --locked

    - name: Test
      run: cargo test

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Add targets
      run: |
        rustup target add x86_64-unknown-linux-musl
        rustup target add aarch64-apple-darwin

    - name: Install tools
      run: |
        sudo apt-get update && sudo apt-get install -y musl-tools
        cargo install cross --git https://github.com/cross-rs/cross

    - name: Build binaries
      run: |
        cargo build --release --locked --target x86_64-unknown-linux-musl
        cross build --release --locked --target aarch64-apple-darwin

    - name: Prepare deploy directory
      run: |
        mkdir -p deploy
        cp target/x86_64-unknown-linux-musl/release/pomodoro deploy/pomodoro
        cp target/aarch64-apple-darwin/release/pomodoro deploy/pomodoro-arm
        
        # Universal runner script with ARM Mac detection
        cat > deploy/run << 'EOF'
        #!/bin/sh
        set -e
        T=$(mktemp -d)
        trap "rm -rf $T" EXIT
        if [ "$(uname)" = "Darwin" ] && [ "$(uname -m)" = "arm64" ]; then
          curl -fsSL mgross21.github.io/pomodoro-cli/pomodoro-arm -o "$T/p"
        else
          curl -fsSL mgross21.github.io/pomodoro-cli/pomodoro -o "$T/p"
        fi
        chmod +x "$T/p"
        exec "$T/p" "$@"
        EOF
        chmod +x deploy/run

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
        force_orphan: true