name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Build
      run: cargo build --release --locked

    - name: Test
      run: cargo test

  build-binaries:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            name: pomodoro
          - os: macos-latest
            target: aarch64-apple-darwin
            name: pomodoro-arm
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        target: ${{ matrix.target }}
        override: true

    - name: Install musl tools (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y musl-tools

    - name: Build binary
      run: cargo build --release --locked --target ${{ matrix.target }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: target/${{ matrix.target }}/release/pomodoro

  deploy:
    needs: build-binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Prepare deploy directory
      run: |
        mkdir -p deploy
        cp pomodoro/pomodoro deploy/pomodoro
        cp pomodoro-arm/pomodoro deploy/pomodoro-arm
        
        # Universal runner script with ARM Mac detection
        cat > deploy/run << 'EOF'
        #!/bin/sh
        set -e
        T=$(mktemp -d)
        trap "rm -rf $T" EXIT
        if [ "$(uname)" = "Darwin" ] && [ "$(uname -m)" = "arm64" ]; then
          curl -fsSL mgross21.github.io/pomodoro-cli/pomodoro-arm -o "$T/p"
        else
          curl -fsSL mgross21.github.io/pomodoro-cli/pomodoro -o "$T/p"
        fi
        chmod +x "$T/p"
        exec "$T/p" "$@"
        EOF
        chmod +x deploy/run

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
        force_orphan: true